### ISSUE TITLE
The ground truth is wrong or missing

### ISSUE THREAD

**Issue by matemat13** [TIERS/multi_lidar_multi_uav_dataset#2]
Hi. It's appreciated that you provide the ground-truth poses of the target. However, there are two major problems:

1. In some datasets (e.g. `TelloOut02.bag`) the ground-truth topic (`/vrpn_client_node/tello/pose` in this case) seems to be incorrect or missing for most of the time.
2. There is no transformation defined between the `world` frame (in which the ground truth is specified) and the sensor frames (i.e. `base_link` or `os_sensor` etc.).

Because of this, it is hard to evaluate accuracy of detection approaches, limiting the usefulness of the provided data :(

**Comment by IacopomC** [comment]
The transformation is unknown, to compute the accuracy we used this tool: https://github.com/MichaelGrupp/evo . It's quite straightforward and very accurate. It also doesn't need the initial transformation.

Also, the ground truth is correct and not missing in any of the rosbags. All the trajectories in the project page have been generated using the ground truth
