### ISSUE TITLE
Unable to Download the rosbag

### ISSUE THREAD

**Issue by hkwww** [TIERS/multi_lidar_multi_uav_dataset#4]
Thank you for making your dataset available to the public. I am eager to work with it; however, I encountered an issue when attempting to download the rosbag file. The webpage displays a "404 File Not Found" error.

Could you kindly provide me with an updated download link?

**Comment by IacopomC** [comment]
Thank you for bringing this up, the server seemed to be down for some reason. You should be able to download the rosbags again
